# Generated by Django 4.1.1 on 2022-09-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract_api', '0002_alter_receipt_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='order',
            new_name='customer_order',
        ),
    ]
